CREATE table GLOBOMART.PRICE 
(ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 5000, INCREMENT BY 1),
PRODUCTID INTEGER,
PRICE DECIMAL(11,2),
PRIMARY KEY (ID));

DROP TABLE GLOBOMART.PRODUCT